import { getUser } from "@/actions";
import Modals from "./components/Modals/Modals";
import Navbar from "./components/Navbar";
import "./globals.css";
import MediaProvider from "./providers/MediaProvider";
import CommentProvider from "./providers/CommentProvider";
import ChatBoxModalContainer from "./components/ChatBoxModal/ChatBoxModalContainer";
import ChatBoxModal from "./components/ChatBoxModal/ChatBoxModal";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className=" bg-gray-100">
        <MediaProvider>
          <CommentProvider>
            <Modals />
            <Navbar />
            <ChatBoxModalContainer>
              <ChatBoxModal />
            </ChatBoxModalContainer>
            {children}
            {/* <StoryUploadModal /> */}
          </CommentProvider>
        </MediaProvider>
      </body>
    </html>
  );
}
