import Modals from "./components/Modals/Modals";

import Navbar from "./components/Navbar";
import "./globals.css";
import MediaProvider from "./providers/MediaProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-gray-100">
        <MediaProvider>
          <Modals />
          <Navbar />
          {/* <StoryUploadModal /> */}
          {children}
        </MediaProvider>
      </body>
    </html>
  );
}
